stages:
  - unittesting_source
  - build
  - unittesting_binaries
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

unittesting_source:
  image: $CI_REGISTRY/uspex_python/uspex_again:master
  stage: unittesting_source
  script:
    - nosetests -v .

build:
  image: $CI_REGISTRY/uspex_python/thirdparty/cython:master
  stage: build
  script:
    - find . -name ".git*" | xargs rm -rf
    - mkdir Src
    - mkdir onlytests
    - find . -type d -name "*unittests*" | xargs -I {} -t sh -c 'mkdir -p ./onlytests/$(dirname {}) && mv {} ./onlytests/$(dirname {})'
    - find . -maxdepth 1 -mindepth 1 ! -path ./Src ! -path ./onlytests | xargs -I {} mv {} ./Src/
    - find ./Src -type d -name "*tests*" | xargs rm -rf
    - find ./Src -type f \( -name "*.py" ! -name "__init__.py" \) | xargs -I {} -t sh -c 'cythonize -i {} && rm {}'
    - find ./Src -type f -name "*.c" | xargs -I {} rm {}
  artifacts:
    paths:
      - Src
      - onlytests
    expire_in: 1 mos 1 day

unittesting_binaries:
  image: $CI_REGISTRY/uspex_python/uspex_again:master
  stage: unittesting_binaries
  script:
    - cp -r ./onlytests/* ./Src
    - cd ./Src
    - nosetests -v .

trigger_build:
  image: $CI_REGISTRY/uspex_python/thirdparty/aux:master
  stage: deploy
  script:
    - "curl -X POST -F token=$USPEX_AGAIN_BUILD_TRIGGER -F ref=master -F variables[SUBPROJECT_ID]=$CI_PROJECT_ID -F variables[SUBPROJECT_REF]=$CI_COMMIT_REF_SLUG https://git.uspex-team.org/api/v4/projects/59/trigger/pipeline"
  except:
    - triggers
