stages:
  - test_phase1
  - build_phase1
  - test_phase2
  - build_phase2
  - test_phase3
  - build_phase3

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test_sources:
  image: $CI_REGISTRY/uspex_python/thirdparty:master
  stage: test_phase1
  script:
    - pip install pip-tools
    - pip-compile -o requirements.txt pyproject.toml
    - pip-sync
    - pip install nose
    - cd USPEX
    - nosetests -v .

build_whl38:
  image: python:3.8
  stage: build_phase1
  script:
    - pip install build
    - find ./USPEX -type d -name "*unittests*" | xargs rm -r
    - python -m build --wheel
  artifacts:
    paths:
      - dist/uspex-*-cp38-cp38-linux_x86_64.whl
    expire_in: 1 mos 1 day

test_binaries:
  image: $CI_REGISTRY/uspex_python/thirdparty:master
  stage: test_phase2
  script:
    - pip install pip-tools
    - pip-compile -o requirements.txt pyproject.toml
    - pip-sync
    - pip install nose
    - mkdir binaries && unzip dist/uspex-*-cp38-cp38-linux_x86_64.whl -d binaries
    - find ./USPEX -type d -name "*unittests*" | xargs -I {} -t sh -c 'mkdir -p ./binaries/$(dirname {}) && mv {} ./binaries/$(dirname {})'
    - cd binaries/USPEX
    - nosetests -v .

test_package:
  image: $CI_REGISTRY/uspex_python/thirdparty:master
  stage: test_phase3
  script:
    - pip install pip-tools
    - pip-compile -o requirements.txt pyproject.toml
    - pip-sync
    - pip install dist/uspex-*-cp38-cp38-linux_x86_64.whl
    - cd testFolder
    - uspex -r
  artifacts:
    paths:
      - testFolder

build_documentation:
  image: python:3.8
  stage: build_phase3
  script:
    - pip install pip-tools
    - pip-compile -o requirements.txt pyproject.toml
    - pip-sync
    - pip install sphinx dist/uspex-*-cp38-cp38-linux_x86_64.whl
    - sphinx-build -b html sphinx build_docs
  artifacts:
    paths:
      - build_docs
    expire_in: 1 mos 1 day

build_whl39:
  image: python:3.9
  stage: build_phase3
  script:
    - pip install build
    - find ./USPEX -type d -name "*unittests*" | xargs rm -r
    - python -m build --wheel
  artifacts:
    paths:
      - dist/uspex-*-cp39-cp39-linux_x86_64.whl

build_whl310:
  image: python:3.10
  stage: build_phase3
  script:
    - pip install build
    - find ./USPEX -type d -name "*unittests*" | xargs rm -r
    - python -m build --wheel
  artifacts:
    paths:
      - dist/uspex-*-cp310-cp310-linux_x86_64.whl

