from setuptools import Extension, setup
from Cython.Build import cythonize
from setuptools.command.build_ext import build_ext


class build_uspex(build_ext):

    """Build all extensions and copy data files to build directory."""

    description = build_ext.description + " and copy data files to build directory."

    def run(self):
        build_ext.run(self)
        build_py = self.get_finalized_command('build_py')
        build_py.build_lib = self.build_lib
        build_py.build_package_data()

extensions = [
    Extension("USPEX.GlobalOptimizer", ["USPEX/GlobalOptimizer.py"]),
    Extension("USPEX.Target", ["USPEX/Target.py"]),
    Extension("USPEX.SystemPool", ["USPEX/SystemPool.py"]),
    Extension("USPEX.Fitness", ["USPEX/Fitness.py"]),
    Extension("USPEX.ConvexHull", ["USPEX/ConvexHull.py"]),
    Extension("USPEX.VariationOperators", ["USPEX/VariationOperators.py"]),
    Extension("USPEX.paretoRanking", ["USPEX/paretoRanking.py"]),
    Extension("USPEX.Presets", ["USPEX/Presets.py"]),
    Extension("USPEX.Selection.USPEXClassic", ["USPEX/Selection/USPEXClassic.py"]),
    Extension("USPEX.Selection.Autofrac", ["USPEX/Selection/Autofrac.py"]),
    Extension("USPEX.SpaceGroups.SpaceGroups3D", ["USPEX/SpaceGroups/SpaceGroups3D.py"]),
    Extension("USPEX.SpaceGroups.TopologicalNet", ["USPEX/SpaceGroups/TopologicalNet.py"]),
    Extension("USPEX.XRay.PowderSpectrumAnalyzer", ["USPEX/XRay/PowderSpectrumAnalyzer.py"]),
    Extension("USPEX.XRay.SingleCrystalSpectrumAnalyzer", ["USPEX/XRay/SingleCrystalSpectrumAnalyzer.py"]),
    Extension("USPEX.XRay.get_reflections", ["USPEX/XRay/get_reflections.py"]),
    Extension("USPEX.Atomistic.AtomicPrimitives", ["USPEX/Atomistic/AtomicPrimitives.py"]),
    Extension("USPEX.Atomistic.Bonds", ["USPEX/Atomistic/Bonds.py"]),
    Extension("USPEX.Atomistic.CellUtility", ["USPEX/Atomistic/CellUtility.py"]),
    Extension("USPEX.Atomistic.CompositionCH", ["USPEX/Atomistic/CompositionCH.py"]),
    Extension("USPEX.Atomistic.CompositionSpace", ["USPEX/Atomistic/CompositionSpace.py"]),
    Extension("USPEX.Atomistic.Conditions", ["USPEX/Atomistic/Conditions.py"]),
    Extension("USPEX.Atomistic.Element", ["USPEX/Atomistic/Element.py"]),
    Extension("USPEX.Atomistic.GCH", ["USPEX/Atomistic/GCH.py"]),
    Extension("USPEX.Atomistic.IonDistances", ["USPEX/Atomistic/IonDistances.py"]),
    Extension("USPEX.Atomistic.RadialDistributionUtility", ["USPEX/Atomistic/RadialDistributionUtility.py"]),
    Extension("USPEX.Atomistic.SimpleMoleculeUtility", ["USPEX/Atomistic/SimpleMoleculeUtility.py"]),
    Extension("USPEX.Atomistic.Slab", ["USPEX/Atomistic/Slab.py"]),
    Extension("USPEX.Atomistic.Transformation", ["USPEX/Atomistic/Transformation.py"]),
    Extension("USPEX.Atomistic.optLattice", ["USPEX/Atomistic/optLattice.py"]),
    Extension("USPEX.Atomistic.softmodes.calcHardness", ["USPEX/Atomistic/softmodes/calcHardness.py"]),
    Extension("USPEX.Atomistic.softmodes.calcSoftModes", ["USPEX/Atomistic/softmodes/calcSoftModes.py"]),
    Extension("USPEX.Atomistic.softmodes.getMinimalGraphBonds", ["USPEX/Atomistic/softmodes/getMinimalGraphBonds.py"]),
    Extension("USPEX.Atomistic.Operators.Heredity", ["USPEX/Atomistic/Operators/Heredity.py"]),
    Extension("USPEX.Atomistic.Operators.Permutation", ["USPEX/Atomistic/Operators/Permutation.py"]),
    Extension("USPEX.Atomistic.Operators.RandSym", ["USPEX/Atomistic/Operators/RandSym.py"]),
    Extension("USPEX.Atomistic.Operators.RandTop", ["USPEX/Atomistic/Operators/RandTop.py"]),
    Extension("USPEX.Atomistic.Operators.Rotation", ["USPEX/Atomistic/Operators/Rotation.py"]),
    Extension("USPEX.Atomistic.Operators.Seeds", ["USPEX/Atomistic/Operators/Seeds.py"]),
    Extension("USPEX.Atomistic.Operators.Softmodemutation", ["USPEX/Atomistic/Operators/Softmodemutation.py"]),
    Extension("USPEX.Atomistic.Operators.Transmutation", ["USPEX/Atomistic/Operators/Transmutation.py"]),
    Extension("USPEX.Atomistic.Operators.symope.fix_latticeStokes_after", ["USPEX/Atomistic/Operators/symope/fix_latticeStokes_after.py"]),
    Extension("USPEX.Atomistic.Operators.symope.Get_Final_Struc", ["USPEX/Atomistic/Operators/symope/Get_Final_Struc.py"]),
    Extension("USPEX.Atomistic.Operators.symope.Get_Init_Lattice", ["USPEX/Atomistic/Operators/symope/Get_Init_Lattice.py"]),
    Extension("USPEX.Atomistic.Operators.symope.GetPermutation", ["USPEX/Atomistic/Operators/symope/GetPermutation.py"]),
    Extension("USPEX.Atomistic.Operators.symope.GetPrimitiveCell", ["USPEX/Atomistic/Operators/symope/GetPrimitiveCell.py"]),
    Extension("USPEX.Atomistic.Operators.symope.latConverter", ["USPEX/Atomistic/Operators/symope/latConverter.py"]),
    Extension("USPEX.Atomistic.Operators.symope.Read_Stokes_output", ["USPEX/Atomistic/Operators/symope/Read_Stokes_output.py"]),
    Extension("USPEX.Atomistic.Operators.symope.spaceGroups", ["USPEX/Atomistic/Operators/symope/spaceGroups.py"]),
    Extension("USPEX.Atomistic.Operators.symope.splitBigCell", ["USPEX/Atomistic/Operators/symope/splitBigCell.py"]),
    Extension("USPEX.Atomistic.Operators.symope.symope_crystal", ["USPEX/Atomistic/Operators/symope/symope_crystal.py"]),
    Extension("USPEX.Atomistic.Operators.symope.unitCellFromPrimitive", ["USPEX/Atomistic/Operators/symope/unitCellFromPrimitive.py"]),
    Extension("USPEX.Atomistic.Operators.symope.Write_Stokes_input", ["USPEX/Atomistic/Operators/symope/Write_Stokes_input.py"]),

]
setup(
    name="USPEX",
    packages=["USPEX"],
    package_dir={"USPEX": "USPEX/."},
    package_data={
        "USPEX": [
            "__init__.py",
            "components.py",
            "main.py",
            "GenerationController.py",
            "Atomistic/__init__.py",
            "Atomistic/softmodes/__init__.py",
            "Atomistic/Operators/__init__.py",
            "Atomistic/Operators/idealnets.json",
            "Atomistic/Operators/symope/__init__.py",
            "Atomistic/Operators/symope/spacegroup/data/data_diperiodic.txt",
            "Atomistic/Operators/symope/spacegroup/data/data_space.txt",
            "Atomistic/Operators/symope/spacegroup/data/data_space2d.txt",
            "Atomistic/Operators/symope/spacegroup/data/data_wyckoff.txt",
            "Calculators/__init__.py",
            "Calculators/ABINIT_Interface.py",
            "Calculators/GULP_Interface.py",
            "Calculators/LAMMPS_Interface.py",
            "Calculators/LifeState.py",
            "Calculators/MLIP_Interface.py",
            "Calculators/PWmat_Interface.py",
            "Calculators/QE_Interface.py",
            "Calculators/VASP_Interface.py",
            "Calculators/Common/__init__.py",
            "Calculators/Common/Connector.py",
            "Calculators/Common/KPoints.py",
            "Calculators/Common/MLIPCfgParser.py",
            "Calculators/Common/Screen.py",
            "Calculators/Common/SHELL_Calculator.py",
            "Calculators/Common/SHELL_Interface.py",
            "Calculators/TaskManagers/__init__.py",
            "Calculators/TaskManagers/BSUB.py",
            "Calculators/TaskManagers/QSUB.py",
            "Calculators/TaskManagers/SBATCH.py",
            "Calculators/TaskManagers/Screen_TM.py",
            "Calculators/TaskManagers/SHELL.py",
            "Calculators/TaskManagers/TaskManager.py",
            "Controllers/__init__.py",
            "IO/__init__.py",
            "IO/compileParams.py",
            "IO/CrystalRepresentation.py",
            "IO/formatters.py",
            "IO/InputParser.py",
            "IO/InputConverter.py",
            "IO/RawParser.py",
            "IO/OutputRepresentation.py",
            "IO/USPEXClassicRepresentation.py",
            "IO/read_molecule.py",
            "Selection/__init__.py",
            "SpaceGroups/__init__.py",
            "SpaceGroups/decompositions.json",
            "XRay/__init__.py",
            "XRay/atomic_scattering_params.json"
        ],
    },
    ext_modules=cythonize(extensions, language_level=3),
    cmdclass={'build_uspex': build_uspex},
)
