[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "USPEX"
requires-python = ">=3.8"
dependencies = ["ase", "pymatgen", "abipy", "asyncssh", "pandas", "scikit-learn", "prettytable", "parsec", "pyxtal", "torch"]
dynamic = ["version"]

[project.scripts]
uspex="USPEX.main:main"
