from setuptools import Extension, setup
from Cython.Build import cythonize

extensions = [
    Extension("USPEX.Optimizers.GlobalOptimizer", ["USPEX/Optimizers/GlobalOptimizer.py"]),
    Extension("USPEX.Optimizers.ModelOptimizer", ["USPEX/Optimizers/ModelOptimizer.py"]),
    Extension("USPEX.Optimizers.Target", ["USPEX/Optimizers/Target.py"]),
    Extension("USPEX.Optimizers.SystemPool", ["USPEX/Optimizers/SystemPool.py"]),
    Extension("USPEX.Fitness.Fitness", ["USPEX/Fitness/Fitness.py"]),
    Extension("USPEX.Fitness.ConvexHull", ["USPEX/Fitness/ConvexHull.py"]),
    Extension("USPEX.Fitness.paretoRanking", ["USPEX/Fitness/paretoRanking.py"]),
    Extension("USPEX.Selection.USPEXClassic", ["USPEX/Selection/USPEXClassic.py"]),
    Extension("USPEX.Selection.Antiseeds", ["USPEX/Selection/Antiseeds.py"]),
    Extension("USPEX.SpaceGroups.SpaceGroups3D", ["USPEX/SpaceGroups/SpaceGroups3D.py"]),
    Extension("USPEX.XRay.PowderSpectrumAnalyzer", ["USPEX/XRay/PowderSpectrumAnalyzer.py"]),
    Extension("USPEX.XRay.SingleCrystalSpectrumAnalyzer", ["USPEX/XRay/SingleCrystalSpectrumAnalyzer.py"]),
    Extension("USPEX.XRay.get_reflections", ["USPEX/XRay/get_reflections.py"]),
    Extension("USPEX.Atomistic.AtomicPrimitives", ["USPEX/Atomistic/AtomicPrimitives.py"]),
    Extension("USPEX.Atomistic.SymmetricStructure", ["USPEX/Atomistic/SymmetricStructure.py"]),
    Extension("USPEX.Atomistic.ElasticML", ["USPEX/Atomistic/ElasticML.py"]),
    Extension("USPEX.Atomistic.BondUtility", ["USPEX/Atomistic/BondUtility.py"]),
    Extension("USPEX.Atomistic.CellUtility", ["USPEX/Atomistic/CellUtility.py"]),
    Extension("USPEX.Atomistic.EnvironmentUtility", ["USPEX/Atomistic/EnvironmentUtility.py"]),
    Extension("USPEX.Atomistic.JunctionUtility", ["USPEX/Atomistic/JunctionUtility.py"]),
    Extension("USPEX.Atomistic.CompositionCH", ["USPEX/Atomistic/CompositionCH.py"]),
    Extension("USPEX.Atomistic.CompositionSpace", ["USPEX/Atomistic/CompositionSpace.py"]),
    Extension("USPEX.Atomistic.Conditions", ["USPEX/Atomistic/Conditions.py"]),
    Extension("USPEX.Atomistic.Element", ["USPEX/Atomistic/Element.py"]),
    Extension("USPEX.Atomistic.GCH", ["USPEX/Atomistic/GCH.py"]),
    Extension("USPEX.Atomistic.Constraints", ["USPEX/Atomistic/Constraints.py"]),
    Extension("USPEX.Atomistic.RadialDistributionUtility", ["USPEX/Atomistic/RadialDistributionUtility.py"]),
    Extension("USPEX.Atomistic.SimpleMoleculeUtility", ["USPEX/Atomistic/SimpleMoleculeUtility.py"]),
    Extension("USPEX.Atomistic.Slab", ["USPEX/Atomistic/Slab.py"]),
    Extension("USPEX.Atomistic.Transformation", ["USPEX/Atomistic/Transformation.py"]),
    Extension("USPEX.Atomistic.VolumeEstimator", ["USPEX/Atomistic/VolumeEstimator.py"]),
    Extension("USPEX.Atomistic.Operators.Heredity", ["USPEX/Atomistic/Operators/Heredity.py"]),
    Extension("USPEX.Atomistic.Operators.Permutation", ["USPEX/Atomistic/Operators/Permutation.py"]),
    Extension("USPEX.Atomistic.Operators.RandSym", ["USPEX/Atomistic/Operators/RandSym.py"]),
    Extension("USPEX.Atomistic.Operators.RandSymPyXtal", ["USPEX/Atomistic/Operators/RandSymPyXtal.py"]),
    Extension("USPEX.Atomistic.Operators.RandTop", ["USPEX/Atomistic/Operators/RandTop.py"]),
    Extension("USPEX.Atomistic.Operators.Rotation", ["USPEX/Atomistic/Operators/Rotation.py"]),
    Extension("USPEX.Atomistic.Operators.Seeds", ["USPEX/Atomistic/Operators/Seeds.py"]),
    Extension("USPEX.Atomistic.Operators.Softmodemutation", ["USPEX/Atomistic/Operators/Softmodemutation.py"]),
    Extension("USPEX.Atomistic.Operators.Transmutation", ["USPEX/Atomistic/Operators/Transmutation.py"]),
    Extension("USPEX.Atomistic.Operators.AddAtom", ["USPEX/Atomistic/Operators/AddAtom.py"]),
    Extension("USPEX.Atomistic.Operators.RemoveAtom", ["USPEX/Atomistic/Operators/RemoveAtom.py"]),
    Extension("USPEX.Atomistic.Operators.TeleportAtom", ["USPEX/Atomistic/Operators/TeleportAtom.py"]),
    Extension("USPEX.Atomistic.Operators.CoreAdsorbantRandomGenerator", ["USPEX/Atomistic/Operators/CoreAdsorbantRandomGenerator.py"]),
    Extension("USPEX.Atomistic.Operators.symope.fix_latticeStokes_after", ["USPEX/Atomistic/Operators/symope/fix_latticeStokes_after.py"]),
    Extension("USPEX.Atomistic.Operators.symope.Get_Final_Struc", ["USPEX/Atomistic/Operators/symope/Get_Final_Struc.py"]),
    Extension("USPEX.Atomistic.Operators.symope.Get_Init_Lattice", ["USPEX/Atomistic/Operators/symope/Get_Init_Lattice.py"]),
    Extension("USPEX.Atomistic.Operators.symope.GetPermutation", ["USPEX/Atomistic/Operators/symope/GetPermutation.py"]),
    Extension("USPEX.Atomistic.Operators.symope.GetPrimitiveCell", ["USPEX/Atomistic/Operators/symope/GetPrimitiveCell.py"]),
    Extension("USPEX.Atomistic.Operators.symope.latConverter", ["USPEX/Atomistic/Operators/symope/latConverter.py"]),
    Extension("USPEX.Atomistic.Operators.symope.Read_Stokes_output", ["USPEX/Atomistic/Operators/symope/Read_Stokes_output.py"]),
    Extension("USPEX.Atomistic.Operators.symope.spaceGroups", ["USPEX/Atomistic/Operators/symope/spaceGroups.py"]),
    Extension("USPEX.Atomistic.Operators.symope.splitBigCell", ["USPEX/Atomistic/Operators/symope/splitBigCell.py"]),
    Extension("USPEX.Atomistic.Operators.symope.symope_crystal", ["USPEX/Atomistic/Operators/symope/symope_crystal.py"]),
    Extension("USPEX.Atomistic.Operators.symope.symope_cluster", ["USPEX/Atomistic/Operators/symope/symope_cluster.py"]),
    Extension("USPEX.Atomistic.Operators.symope.unitCellFromPrimitive", ["USPEX/Atomistic/Operators/symope/unitCellFromPrimitive.py"]),
    Extension("USPEX.Atomistic.Operators.symope.Write_Stokes_input", ["USPEX/Atomistic/Operators/symope/Write_Stokes_input.py"]),
]

setup(
    ext_modules=cythonize(extensions, language_level=3),
)
