#!/bin/sh
#PBS -l nodes=1:ppn=8,walltime=48:00:00 
#PBS -N HEA_MD
#PBS -j oe
#PBS -V 
cd ${PBS_O_WORKDIR}

module load MPI/impi/2017.0.4 MKL/2017.4.239
mpirun /gss/home/a.maltsev/softs/VASP/vasp_std >> log
