#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --partition=lenovo
#SBATCH --time=24:00:00

#SBATCH -J  USPEX-8Ss0
#SBATCH -i  abinit.files
#SBATCH -o  output
#SBATCH -e  error

module load abinit/abinit9.1.3; mpirun abinit
